list            : $/martin/routes/models/route/columns.yaml
modelClass      : Martin\Routes\Models\Route
title           : martin.routes::lang.controllers.routes.title
noRecordsMessage: 'backend::lang.list.no_records'
showSetup       : true
showCheckboxes  : true
recordUrl       : 'martin/routes/routes/update/:id'
toolbar         :
    buttons: partials/list_toolbar
    search :
        prompt: 'backend::lang.list.search_prompt'